---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/home
  label: Home Content
  create: all
  match: "**/*.md"
- type: directory
  path: src/content/team
  label: Team
  create: all
  match: "**/*.md"
- type: directory
  path: src/content/founders
  label: Founders
  create: documents
  match: "**/*.md"
- type: directory
  path: src/content/contact
  label: Contact
  create: all
  match: "**/*.md"
upload_dir: public/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - DEPLOY_PREVIEW=true
  - SHELL=/bin/bash
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build:watch
